name: Generar changelog

on:
  push:
    branches:
      - master

jobs:
  changelog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generar archivo CHANGELOG.md
        run: |
          echo "## Últimos cambios" > CHANGELOG.md
          git log --pretty=format:"- %h %s (%an, %ad)" --date=short >> CHANGELOG.md
          cat CHANGELOG.md

      - name: Configurar autor del commit
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Commit y push de CHANGELOG.md
        run: |
          git add CHANGELOG.md
          git diff-index --quiet HEAD || git commit -m "Actualizar CHANGELOG.md [skip ci]"
          git push
