name: Prevenir merges con conflictos

on:
  push:
    branches:
      - master

jobs:
  check-conflicts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Buscar conflictos en archivos
        run: |
          echo "🔍 Buscando conflictos..."
          if grep -r "<<<<<<<" .; then
            echo "❌ Conflictos detectados. Corrígelos antes de subir."
            exit 1
          else
            echo "✅ Sin conflictos."
          fi