#Agregando el composer_audit.yml
name: Auditoría de dependencias

on:
  push:
    branches: [ master ]

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Instalar PHP y Composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Ejecutar auditoría
        run: |
          composer install
          composer audit || echo "Auditoría completada"
